### ISSUE TITLE
Consulta de "Role não foi encontrada" pela imagem #Docker

### ISSUE THREAD

**Issue by pauloruszel** [pauloruszel/desafio-angular-spring-boot#1]
`app    | 2020-12-23 12:35:34.948 ERROR 1 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: Error: Role não encontrada.] with root cause
app    | 
app    | java.lang.RuntimeException: Error: Role não encontrada.
app    | 	at br.net.mirante.colaborador.resource.AuthResource.lambda$registrarUsuario$0(AuthResource.java:99) ~[classes!/:1.0.0-SNAPSHOT]
app    | 	at java.base/java.util.Optional.orElseThrow(Unknown Source) ~[na:na]
app    | 	at br.net.mirante.colaborador.resource.AuthResource.registrarUsuario(AuthResource.java:99) ~[classes!/:1.0.0-SNAPSHOT]
app    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
app    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
app    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
app    | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]`

**Comment by pauloruszel** [comment]
![image](https://user-images.githubusercontent.com/12766450/102997894-dde6ac80-4504-11eb-8073-883dcaa216d8.png)
